"""rename department

Revision ID: ec1f1ee84e8f
Revises: d988de9fcca0
Create Date: 2024-06-27 21:44:20.794045

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ec1f1ee84e8f'
down_revision = 'd988de9fcca0'
branch_labels = None
depends_on = None




def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.rename_table('department', 'departments')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.rename_table('departments', 'department')
    # ### end Alembic commands ###